name: Deploy to Production

on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened ]

# env:
#   AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
#   AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}

jobs:
  something-step:
    runs-on: ubuntu-latest
    name: "Something step"
    steps:
      - run: echo Something step

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    name: "Deploy production"
    if: github.event.pull_request.merged == true
    steps:
      - run: echo Deploy production