name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - "**.jsx"
      - "**.json"
      - "**.ts"
      - "**.yml"

# env:
#   AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
#   AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}

jobs:
  something-step:
    runs-on: ubuntu-latest
    name: "Something step"
    steps:
      - run: echo Something step

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    name: "Deploy production"
    steps:
      - run: echo Deploy production