name: Deploy CoinTap App to AWS S3

on:
  push:
    branches:
      - dev
    paths: 
      - "**.jsx"
      - "**.json"
      - "**.ts"
      - "**.yml"
  workflow_run:
    workflows: [Testing]
    types: [completed]
  
# env:
#   AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
#   AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Unit Test!!!
  automation-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Automation Test!!!
  
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    name: "Upload app to AWS S3"
    needs: [unit-test, automation-test]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_S3_REGION}}

      

      - name: Copy files to the test website with the AWS CLI
        run: |
          echo hello 312312 > ./hello_world.txt
          aws s3 cp ./hello_world.txt s3://${{secrets.AWS_S3_BUCKET}}