name: Testing
# Run testing when there are any new pull request
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - dev
      - v*
      - gitlab-cicd
      - "!branch-ignore/**"

jobs:
  install-package:
    runs-on: ubuntu-latest
    name: "Install package before"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Unit Test!!!
  automation-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Automation Test!!!
